project:
  type: book

execute:
  freeze: auto

book:
  title: "DSA4199: Deep Learning for Evaluation of Synthetic Speech"
  author: "Li Yang Hew"
  date: "2/6/2024"
  back-to-top-navigation: true
  page-navigation: true
  repo-url: https://github.com/hewliyang/fyp
  downloads: [pdf]
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - tts.qmd
    - related-work.qmd
    - experiments.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



